== Data publishing
=== Publishing
==== Publishing through the IPT
https://ipt.gbif.org/manual/en/[IPT manual] (embed here?)

https://github.com/gbif/ipt/wiki/howToPublish[Wiki: how to publish] (to be retired?)

==== Publishing with the (registry) API (link to API topic)
https://www.gbif.org/developer/registry[Registry API] (or just link to the API page?)

==== Other publishing methods
Other publishing methods exist besides the IPT and the API. More information can be found in this https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/[blogpost] 

=== Dataset classes
Dataset can be published in four different formats:

* Metadata-only
* Checklist
* Occurrence
* Sampling event

Generally, the data quality increases from metadata-only to sampling event datasets. 

==== Data quality recommendations
You can familiarize yourself with the requirements of each dataset class https://www.gbif.org/data-quality-requirements[here]

=== Tools to quality check your publication
==== Dataset validator
The dataset validator can be used to https://www.gbif.org/tools/data-validator/about[validate] zipped Darwin core archive folders

==== Species matching
==== Species API (link to API topic)
==== Test IPT

=== The meaning of flags and issues and how you should deal with them 

=== Data publishing FAQ
* change occurrence IDs
* citations
